### ISSUE TITLE
EOFException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [josaluntu/ksoap2-android#178]
```
On some devices (like S4 with 4.3) when i use HttpTransportSE.call() sometime 
(30% of times) i receive this exception. if I retry all done ok

java.io.EOFException
    at libcore.io.Streams.readAsciiLine(Streams.java:203)
    at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
    at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)
    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
    at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
    at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
    at org.ksoap2.transport.HttpsServiceConnectionSE.getResponseCode(HttpsServiceConnectionSE.java:107)
    at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:197)
    at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:118)
```

Original issue reported on code.google.com by `xan.scale` on 12 Dec 2013 at 4:57

**Comment by GoogleCodeExporter** [comment]
```
version 3.1.1 have this problem
version 3.0.0 seams works fine
```

Original comment by `xan.scale` on 13 Dec 2013 at 10:39

**Comment by GoogleCodeExporter** [comment]
```
version 2.5.4 have this problem
```

Original comment by `yangwend...@163.com` on 26 Jan 2014 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
Can you provide more info or a pull request that fixes the problem you observe? 
```

Original comment by `mosa...@gmail.com` on 29 Jan 2014 at 6:16

**Comment by GoogleCodeExporter** [comment]
```
i dont know cause of this bug
```

Original comment by `xan.scale` on 30 Jan 2014 at 10:56

**Comment by GoogleCodeExporter** [comment]
```
I am having the same problem , how it get fixed¿
```

Original comment by `xabi.ot...@gmail.com` on 6 Feb 2014 at 10:58

**Comment by GoogleCodeExporter** [comment]
```
I get same error too.
i search thing on google and get this...
"if (Build.VERSION.SDK != null && Build.VERSION.SDK_INT > 13) { 
urlConnect.setRequestProperty("Connection", "close"); }"

Above line will be usable on the case of url openconnection.

How i achieved this things in ksoap2.
```

Original comment by `kundanfo...@gmail.com` on 15 Feb 2014 at 4:56

**Comment by GoogleCodeExporter** [comment]
```
This has been fixed by my pull request for Issue 173. 
https://code.google.com/p/ksoap2-android/issues/detail?id=173&can=1&start=100

This is caused by an android bug, to fix it you need to have the latest code 
from master and retry your call after this exception. I'd suggest a 3 call 
limit. 

Please download from master and test. 
```

Original comment by `islandma...@gmail.com` on 17 Feb 2014 at 4:15

**Comment by GoogleCodeExporter** [comment]
```
version 3.2 still have this problem
```

Original comment by `zhangluf...@gmail.com` on 24 Apr 2014 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
version 3.3 still have this problem
```

Original comment by `sdxia...@gmail.com` on 12 Jul 2014 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
version 3.4 still have this problem . lol
```

Original comment by `xyl...@gmail.com` on 9 Jan 2015 at 12:16

**Comment by GoogleCodeExporter** [comment]
```
Hey guys,

Can you be more specific? Are you still ha ing the problem even with my 
suggested 3 try fix?

Thanks
```

Original comment by `islandma...@gmail.com` on 9 Jan 2015 at 12:53

**Comment by GoogleCodeExporter** [comment]
```
it's appear on 30% of times, so with 3 try i have a 90% of success. but i don't 
like this solution.

i continue to use 3.0.0 that works fine
```

Original comment by `xan.scale` on 9 Jan 2015 at 9:04

**Comment by GoogleCodeExporter** [comment]
```
https://code.google.com/p/ksoap2-android/issues/detail?id=199

seams same bug
```

Original comment by `xan.scale` on 9 Jan 2015 at 9:08

**Comment by GoogleCodeExporter** [comment]
```
3.4 seams works to me
```

Original comment by `xan.scale` on 9 Jan 2015 at 11:17

**Comment by GoogleCodeExporter** [comment]
```
Excellent.
```

Original comment by `mosa...@gmail.com` on 12 Jan 2015 at 7:08
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
3.4 still have this problem.
```

Original comment by `Luocon...@gmail.com` on 31 Jan 2015 at 2:27

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem, and I'm using also ksoap2 3.4.0.

02-01 16:45:22.415  25583-25583/com.studio3s.probrokerrca 
W/IInputConnectionWrapper﹕ getCursorCapsMode on inactive InputConnection
02-01 16:45:22.435  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
libcore.io.Streams.readAsciiLine(Streams.java:203)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:27
4)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.jav
a:486)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
org.ksoap2.transport.ServiceConnectionSE.getResponseCode(ServiceConnectionSE.jav
a:103)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:192)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:118)
02-01 16:45:22.445  25583-25638/com.studio3s.probrokerrca W/System.err﹕ at 
org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:113)

Is there any quick fix? Beside changing to version 3.0.0
```

Original comment by `mihai.re...@3sstudio.com` on 1 Feb 2015 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
i have problem only with note 2 using version 3.4

i don't know why
```

Original comment by `xan.scale` on 19 Mar 2015 at 5:36

**Comment by GoogleCodeExporter** [comment]
```
Hi, I am using the version ksoap2-android-assembly-3.4.0-jar and I am having 
the same problem intermittently.

Error Trace:
08-02 20:37:58.371  
25823-26139/com.androidapp.sroyc07.accessingbluemixservice_serverinfo 
W/System.err﹕ java.io.EOFException
08-02 20:37:58.387  
25823-26139/com.androidapp.sroyc07.accessingbluemixservice_serverinfo 
W/System.err﹕ at libcore.io.Streams.readAsciiLine(Streams.java:203)
08-02 20:37:58.387  
25823-26139/com.androidapp.sroyc07.accessingbluemixservice_serverinfo 
W/System.err﹕ at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560)
08-02 20:37:58.387  
25823-26139/com.androidapp.sroyc07.accessingbluemixservice_serverinfo 
W/System.err﹕ at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813)
08-02 20:37:58.387  
25823-26139/com.androidapp.sroyc07.accessingbluemixservice_serverinfo 
W/System.err﹕ at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:27
4)
08-02 20:37:58.387  
25823-26139/com.androidapp.sroyc07.accessingbluemixservice_serverinfo 
W/System.err﹕ at 
```

Original comment by `escortno...@gmail.com` on 2 Aug 2015 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
Package version ksoap2-android-assembly-3.4.0-jar-with-dependencies.jar have 
this problem, S3 with 4.3.

...
transport.call("\"" + NAMESPACE + METHOD +"\"", envelope);
...

08-15 15:45:54.625: W/System.err(27006): java.io.EOFException
08-15 15:45:54.635: W/System.err(27006):  at 
libcore.io.Streams.readAsciiLine(Streams.java:203)
08-15 15:45:54.635: W/System.err(27006):  at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
08-15 15:45:54.635: W/System.err(27006):  at 
libcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)
08-15 15:45:54.635: W/System.err(27006):  at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:28
3)
08-15 15:45:54.635: W/System.err(27006):  at 
ibcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java
:497)
08-15 15:45:54.635: W/System.err(27006):  at 
org.ksoap2.transport.ServiceConnectionSE.getResponseCode(ServiceConnectionSE.jav
a:103)
08-15 15:45:54.635: W/System.err(27006):  at 
org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:192)
08-15 15:45:54.635: W/System.err(27006):  at 
org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:118)
08-15 15:45:54.635: W/System.err(27006):  at 
org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:113)


```

Original comment by `rafael.p...@gmail.com` on 15 Aug 2015 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
This is tracker is no longer used. Please file a new issue at 
https://github.com/simpligility/ksoap2-android/issues
```

Original comment by `mosa...@gmail.com` on 16 Aug 2015 at 3:26
