### ISSUE TITLE
SocketException:ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [josaluntu/ksoap2-android#185]
```
If the two call a longer time interval
It tells me
java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)

in transport.call() method

↓↓↓↓↓Code↓↓↓↓↓
```

Original issue reported on code.google.com by `sljjyy...@gmail.com` on 11 Mar 2014 at 2:22

Attachments:
- [code.txt](https://storage.googleapis.com/google-code-attachments/ksoap2-android/issue-185/comment-0/code.txt)

**Comment by GoogleCodeExporter** [comment]
```
I have same issue. I try to use the same code to call a wcf service repeatedly 
and if the call interval is 60 seconds, everything is working fine. however if 
the call interval changed to 300 seconds, the first call will be fine but the 
second call will throw the exception like

ERROR [15:05:24]: java.net.SocketException: sendto failed: ECONNRESET 
(Connection reset by peer)
    at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:506)
    at libcore.io.IoBridge.sendto(IoBridge.java:475)
    at java.net.PlainSocketImpl.write(PlainSocketImpl.java:508)
    at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
    at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270)
    at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
    at libcore.net.http.FixedLengthOutputStream.flush(FixedLengthOutputStream.java:49)
    at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:188)
    at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:118)
    at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:113)
    at com.ryarc.webservicehelper.services.PlayerRegister.syncStats(PlayerRegister.java:52)
    at com.ryarc.playersyncprovider.CampaignSyncProvider.SyncStats(CampaignSyncProvider.java:233)
    at com.ryarc.viewmodel.player.AllCMPlayersViewModel$1.run(AllCMPlayersViewModel.java:83)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: libcore.io.ErrnoException: sendto failed: ECONNRESET (Connection 
reset by peer)
    at libcore.io.Posix.sendtoBytes(Native Method)
    at libcore.io.Posix.sendto(Posix.java:146)
    at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
    at libcore.io.IoBridge.sendto(IoBridge.java:473)
    ... 13 more
```

Original comment by `iamzha...@gmail.com` on 14 Mar 2014 at 4:58

**Comment by GoogleCodeExporter** [comment]
```
Which version are you using?

Please look at closed issue 173. This is most likely related to an android bug 
that returns an already closed connection. 
```

Original comment by `islandma...@gmail.com` on 17 Mar 2014 at 2:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `mosa...@gmail.com` on 18 Mar 2014 at 3:42
- Changed state: **Duplicate**
